# Site settings
title: Mauricio Urraco
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nicolas Lair
user_description: blabla
user_title: AI Research Scientist
email: nl[dot]nicolas[dot]lair[at]gmail.com
twitter_username: nico_lr_
github_username:  nicolas-lair
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
